package com.nal.leetcode.string;

/**
 * Created by nishant on 10/02/20.
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output: e
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        if (s == null || t == null)
            return Character.MIN_VALUE;
        int sLength = s.length(), tLength = t.length();
        if (sLength + 1 != tLength)
            return Character.MIN_VALUE;
        char res = t.charAt(tLength - 1);
        for (int i = 0; i < sLength; i++) {
            res ^= s.charAt(i);
            res ^= t.charAt(i);
        }
        return res;
    }

}
